baseURL = "https://finardi.me/"
languageCode = "pt-br"
title = "Thiago Finardi | Blog Pessoal"
defaultContentLanguage = "pt-br"
languageName = "Brazilian Portuguese"
theme = "LoveIt"
themesDir = "themes/"
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true

[author]
  name = "Thiago Finardi"
  email = "tfinardi@gmail.com"
  link = "https://finardi.me/"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
    [[menu.main]]
        identifier = "about"
        pre = "<i class='fas fa-address-card'></i> "
        post = ""
        name = " About"
        url = "/about/"
        title = ""
        weight = 1
    [[menu.main]]
        identifier = "posts"
        pre = "<i class='fas fa-file-alt'></i>"
        name = "Posts"
        url = "/posts/"
        title = "Artigos e Posts"
        weight = 2
    [[menu.main]]
        pre = "<i class='fab fa-linkedin fa-fw'></i>"
        identifier = "linkedin"
        name = "Linkedin"
        url = "https://linkedin.com/in/ThiagoFinardi"
        title = "Linkedin de Thiago Finardi"
        weight = 3  

[params]
    version = "0.2.X"
    defaultTheme = "dark"
    gitRepo = "https://github.com/tfinardi/finardi.me"
    fingerprint = ""
    dateFormat = "02-01-2006"
    images = ["/images/logo.png"]
    description = "Thiago Finardi | Blog Pessoal com artigos técnicos com o objetivo de compartilhar experiências na utilização de ferramentas em laboratório e produção. lém de descrever situações corriqueiras do dia a dia de um Analista de Infraestrutura"
    keywords = ["Thiago Finardi", "Finardi", "Thiago Finardi Blog", "DevOps", "Docker", "Kubernetes", "Ansible", "Virtualização", "Terraform"]
  
    # App icon config
    [params.app]
        title = "Thiago Finardi | Blog pessoal"
        noFavicon = false
        svgFavicon = ""
        themeColor = "#ffffff"
        iconColor = "#5bbad5"
        tileColor = "#da532c"
  
    [params.header]
        desktopMode = "fixed"
        mobileMode = "auto"  
        [params.header.title]
            logo = "/images/logo.png"
            name = "Thiago Finardi"
            pre = "<i class='fas fa-terminal fa-fw'></i>"
            post = ""
            typeit = true

    # Search config
    [params.search]
        enable = true
        type = "lunr"
        contentLength = 4000
        placeholder = ""
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false
    
    # Home page config
    [params.home]
        rss = 10
        # Home page profile
        [params.home.profile]
            enable = true
            gravatarEmail = ""
            avatarURL = "/images/avatar.png"            
            title = "<i class='fas fa-server'></i> Infrastructure Engineer | SysAdmin | DevOps | SRE <i class='fas fa-cloud'></i>"
            subtitle = "Blog com assuntos técnicos, tendo como objetivo compartilhar experiências na utilização de ferramentas em laboratório e produção. Além de descrever situações corriqueiras do dia a dia de um SysAdmin."
            typeit = false
            social = true
            disclaimer = ""
        # Home page posts
        [params.home.posts]
            enable = true
            paginate = 6
    
    # Social config in home page
    [params.social]
        Linkedin = "ThiagoFinardi"
        Telegram = "tfinardi"
        Email = "thiago@finardi.me"
        GitHub = "tfinardi"
        Twitter = "tfinardi"
        Instagram = "tfinardi"
        RSS = true

    [params.section]
        paginate = 10
        dateFormat = "02-01"
        rss = 10    

    [params.list]
        paginate = 10
        dateFormat = "02-01"
        rss = 10

# Footer config
    [params.footer]
        enable = true
        custom = ''
        hugo = true
        copyright = true
        author = true
        since = 2016
        license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = true
    ruby = false
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = false
    [params.page.toc]
        enable = true
        keepStatic = false
        auto = true        
    [params.page.code]
        copy = true
        maxShownLines = 15
    [params.page.share]
        enable = true
        Twitter = true
        Facebook = true
        Linkedin = true
        Whatsapp = true
      
    # Comment config
    [params.page.comment]
        enable = true
        [params.page.comment.disqus]
            enable = true
            shortname = "finardi-me"

    [params.page.library]
        [params.page.library.css]
            finardiCSS = "/finardi.css"           
            
    [params.page.seo]
      images = ["/images/avatar.png"]
        [params.page.seo.publisher]
            name = "Thiago Finardi"
            logoUrl = "/images/avatar.png"

    # Analytics config
    [params.analytics]
        enable = true
        [params.analytics.google]
            id = "UA-155028166-1"
            anonymizeIP = true

[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Markup related configuration in Hugo
[markup]
    # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = true
        noClasses = false
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.renderer]
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]