baseURL = "https://finardi.me/"
defaultContentLanguage = "pt-br"
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "pt-br"
languageName = "Brazilian Portuguese"
theme = "LoveIt"
themesDir = "themes/"
title = "Thiago Finardi | Blog Pessoal"

[author]
email = "tfinardi@gmail.com"
link = "https://finardi.me/"
name = "Thiago Finardi"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[menu]
[[menu.main]]
identifier = "about"
name = " About"
post = ""
pre = "<i class='fas fa-address-card'></i> "
title = ""
url = "/about/"
weight = 1
[[menu.main]]
identifier = "posts"
name = "Posts"
pre = "<i class='fas fa-file-alt'></i>"
title = "Artigos e Posts"
url = "/posts/"
weight = 2
[[menu.main]]
identifier = "linkedin"
name = "Linkedin"
pre = "<i class='fab fa-linkedin fa-fw'></i>"
title = "Linkedin de Thiago Finardi"
url = "https://linkedin.com/in/ThiagoFinardi"
weight = 3

[params]

dateFormat = "02-01-2006"
defaultTheme = "dark"
description = "Thiago Finardi | Blog Pessoal com artigos técnicos com o objetivo de compartilhar experiências na utilização de ferramentas em laboratório e produção. lém de descrever situações corriqueiras do dia a dia de um Analista de Infraestrutura"
fingerprint = ""
gitRepo = "https://github.com/tfinardi/finardi.me"
images = ["/images/logo.png"]
keywords = ["Thiago Finardi", "Finardi", "Thiago Finardi Blog", "DevOps", "SRE", "Docker", "Kubernetes", "Ansible", "Virtualização", "Terraform"]
version = "0.2.X"
# App icon config
[params.app]

iconColor = "#5bbad5"
noFavicon = false
svgFavicon = ""
themeColor = "#ffffff"
tileColor = "#da532c"
title = "Thiago Finardi | Blog pessoal"
[params.header]
desktopMode = "fixed"
mobileMode = "auto"
[params.header.title]
logo = "/images/logo.png"
name = ""
post = ""
pre = ""
typeit = true

# Search config
[params.search]

absoluteURL = false
contentLength = 4000
enable = true
highlightTag = "em"
maxResultLength = 10
placeholder = ""
snippetLength = 30
type = "lunr"
# Home page config
[params.home]
rss = 10
# Home page profile
[params.home.profile]
avatarURL = "/images/avatar.png"
disclaimer = ""
enable = true
gravatarEmail = ""
social = true
subtitle = "Blog com assuntos técnicos, tendo como objetivo compartilhar experiências na utilização de ferramentas em laboratório e produção. Além de descrever situações corriqueiras do dia a dia de um SysAdmin."
title = "<i class='fas fa-server'></i> Infrastructure Engineer | Site Reliability Engineer | DevOps <i class='fas fa-cloud'></i>"
typeit = false
# Home page posts
[params.home.posts]

enable = true
paginate = 6
# Social config in home page
[params.social]
Email = "thiago@finardi.me"
GitHub = "tfinardi"
Instagram = "tfinardi"
Linkedin = "ThiagoFinardi"
RSS = true
Telegram = "tfinardi"
Twitter = "tfinardi"

[params.section]
dateFormat = "02-01"
paginate = 10
rss = 10

[params.list]
dateFormat = "02-01"
paginate = 10
rss = 10

# Footer config
[params.footer]
author = true
copyright = true
custom = ''
enable = true
hugo = true
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
since = 2016

[params.page]
fontawesome = true
fraction = true
hiddenFromHomePage = false
hiddenFromSearch = false
lightgallery = true
linkToMarkdown = true
rssFullText = false
ruby = false
twemoji = false
[params.page.toc]
auto = true
enable = true
keepStatic = false
[params.page.code]
copy = true
maxShownLines = 30
[params.page.share]

Facebook = true
Linkedin = true
Twitter = true
Whatsapp = true
enable = true
# Comment config
[params.page.comment]
enable = true
[params.page.comment.disqus]
enable = true
shortname = "finardi-me"

[params.page.library]
[params.page.library.css]

finardiCSS = "/finardi.css"
[params.page.seo]
images = ["/images/avatar.png"]
[params.page.seo.publisher]
logoUrl = "/images/avatar.png"
name = "Thiago Finardi"

# Analytics config
[params.analytics]
enable = true
[params.analytics.google]
anonymizeIP = true
id = "UA-155028166-1"

[Permalinks]
# posts = ":year/:month/:filename"
posts = ":filename"

# Markup related configuration in Hugo
[markup]
# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
noClasses = false
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
[markup.tableOfContents]
endLevel = 6
startLevel = 2
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML"]
